server:
  port: 8123
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:h2:mem:pvp
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop